# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/researchsummary/',
                'doc_host': 'https://changebio.github.io',
                'git_url': 'https://github.com/changebio/researchsummary/tree/main/',
                'lib_path': 'researchsummary'},
  'syms': {'researchsummary.weekly': {}}}